# Generated by Django 5.1 on 2024-08-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='originalProce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
