# Generated by Django 5.1 on 2024-08-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_product_originalproce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='originalProce',
            new_name='originalPrice',
        ),
    ]
